name: symphony

services:
  symphony-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symphony-web
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - ea-ingress
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      kuma.symphony.group.name: "symphony"
      kuma.symphony-web.http.name: "website"
      kuma.symphony-web.http.parent_name: "symphony"
      kuma.symphony-web.http.url: "https://symphony.atbas.xyz"

networks:
  ea-ingress:
    external: true
